### PR TITLE
Development

### PR DESCRIPTION
**Pull request by Kedyn**
Adds up-to-date mSL for both mIRC and AdiIRC.
Fixes multiple wrong highlighting, such as single line aliases.

### CODE REVIEW

**Comment by gen-angry** [comment]
The msl.json seems to work well on https://github-lightshow.herokuapp.com/ :) I have no issues merging if you want it in. Honestly, this is quite a bit out of my league. I was surprised it even worked at all when I gave it a try, lol.

If you want the repo to make it easier, I can transfer the ownership to you. Figured that adding you as a contributor would let you merge and do stuff but Im not sure exactly what it does.

**Review by gen-angry — APPROVED** [review]

**Comment by Kedyn** [comment]
I do have the access to merge and do multiple things, but I wanted to give you the chance to review.

**Comment by gen-angry** [comment]
Honestly homes, you're doing some real incredible stuff with this. Your VSCode extension is leagues better than the older one that was on the market.

I'm happy to pass it on. It was your work that made it possible in the first place, I feel it's in good hands, and I'm excited to see where it can go.

**Comment by Kedyn** [comment]
I had been working on my on extension since Sophist-UK commented on my pull request on lol2ks repo. I did not have the confidence to release it, but after I saw that part of my work was actually being used it gave me confidence to go for it. So thank you for putting this together. I will try to add as much features on that extension as possible. (Currently thinking of dialog editing support). I am currently just now learning how to use the VSCode API, but hopefully soon we get that error report working. One again thank you, and let's keep working on this to get a cool tool for others to use.

**Comment by gen-angry** [comment]
Started the repo transfer, it should be in your email inbox I think - that's what Github says anyways.

Dialog editing, as in within the msl files themselves? That'd be awesome, I always hated making them by hand.

**Comment by Kedyn** [comment]
Thanks, but won't that cause a problem on linguist's repo? I mean the transfer?


Yeah, a tab in vscode where u can edit a dialog. Thinking you would highlight your dialog code and right click to edit it or create one.

**Comment by gen-angry** [comment]
Shouldn't, the linguist fork I used to actually merge to linguist is long gone. It required a whole lot more files and a few samples.  https://github.com/github/linguist/pull/4652/files - this repo was just a way to link the grammar file. 

If I understand this correctly - https://help.github.com/en/github/administering-a-repository/transferring-a-repository - it sets up a perm-redirect on my account (aside from pages) so it'll carry over anyways. If you decide to push an update upstream to linguist, can modify the link then.

Since I'm a free scrub and you have pro - you owning the repo should allow it the extra benefits as well.

**Comment by Kedyn** [comment]
If that is the case, I gladly accept. Thank you.

**Pull request merged**
